name: Build and Test Python Applications

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker-matrix:
    name: Build and Run Python Scripts
    runs-on: ubuntu-latest

    strategy:
      matrix:
        script:
          # List all Python scripts in the repository
          - EncryptionTool.py
          # Add more scripts here as needed
          # - AnotherScript.py
          # - YetAnotherScript.py

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build --build-arg SCRIPT=${{ matrix.script }} -t python-app:${{ matrix.script }} .

    - name: Run Docker Container
      run: |
        docker run python-app:${{ matrix.script }}
